### ISSUE TITLE
Readd support for managing multiple instances of logstash on the same machine

### ISSUE THREAD

**Issue by clly** [elastic/puppet-logstash#144]
I think it would be good to add managing multiple instances of logstash on the same server.  My use case for this is setting up an architecture like http://logstash.net/docs/1.3.3/tutorials/getting-started-centralized except using a different log shipper to send logs to an input logstash and a second logstash instance for output to elasticsearch.

One of the ways I've thought of how to do this is by changing the config path and having the default file and service file be named the name of the instance (logstashA, logstashB).  I haven't been able to flesh this out though and I've run into several multiple class declaration error when doing a some amount of testing.

**Comment by rtoma** [comment]
+1 (for what its worth).

We currently run our own internal puppet code that supports multiple instances. This was initially created because older logstash version did not allow multiple output threads and we were hitting this limit. Running multiple logstash instances on the same hardware was our method of scaling the throughput of the output threads.

Another reason for wanting to run multiple instances is the ability to run lean configurations instead of one huge configuration. In our setup we have 4 physical boxes running logstash instances per environment. Each environment has its own set of pipelines and variables (e.g. hostnames, filter threads, redis keys).

**Comment by dlmj12** [comment]
+1 - I would also find this useful for reasons stated already.

**Comment by phanisrinivas** [comment]
+1 I would also find this feature very useful

**Comment by ikoniaris** [comment]
This module: https://github.com/haf/puppet-logstash#multi-instance has multi-instance support, maybe you can reimplement it somehow?

**Comment by mirkoebert** [comment]
+1

**Comment by thermz** [comment]
+1
Having a separate logstash configuration instead of **if else** everywhere in one single configuration is sometimes preferable.

**Comment by nehaljwani** [comment]
+1 Same reason as mentioned by @clly

**Comment by putztzu** [comment]
+1
Unlike others who have speculated about things like being single threaded, I also tried simply copying the logstash tree to a new location and then attempting to launch a logstash instance from each tree. 

Because this doesn't work, I'm more inclined to suspect that a single process ID is being used for any/all instances of Logstash, most likely hardcoded. 

If what I suspect is true, then the solution is simple... allow a randomly generated PID whenever logstash is invoked so that each invocation is assigned its own PID.

I guess for now I'll just run my logstash instances on separate machines which is doable but a bit of a headache when I prefer my logstash instances to run on the same machine for management simplicity as long as there are no bottlenecks.

**Comment by psaiz** [comment]
+1

**Comment by helvalius** [comment]
+1

**Comment by gh-amistry** [comment]
Hi @electrical, +1 for me as well. The current Logstash documentation references being able to add more Logstash indexing instances: you can "increase the Elasticsearch cluster’s rate of data consumption by adding more Logstash indexing instances" https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html. Could you elaborate on how this would be done? Multiple Logstash instances would imply the ability to sequence the data between indexers.  Thanks!

**Comment by cdenneen** [comment]
+1

**Comment by becker-IT** [comment]
+1

**Comment by cdenneen** [comment]
:hourglass_flowing_sand: :smiley_cat:

**Comment by mgoritzk** [comment]
+1 as well. It's necesary to build up the ls -> redis -> ls -> es pipeline.

**Comment by SMMAN** [comment]
+1 I agree: this function / possibility IS needed.

**Comment by pdjohe** [comment]
+1 
I'd like to do the following on one machine:
logstash-shipping.conf: (input (multiple types) -> redis)
logstash-indexer.conf: (redis-> grok -> elasticsearch)

When I tried to give to conf files, logstash joins them together so that I got a redis input to redis output and had an endless loop for the same message.

**Comment by alexharv074** [comment]
+1   I also need this feature.  Also I am willing to implement it.

**Comment by salekseev** [comment]
+1

**Comment by rtoma** [comment]
Suggestion: run Logstash in a Docker container using the official image: https://hub.docker.com/_/logstash/
It is an easy way for running multiple instances. Just create configfiles (or dirs) per instance and start that many containers.

YMMV

**Comment by salekseev** [comment]
@rtoma this going in a completely different direction and will require docker which will in turn limit this to only running ok kernels 3.10+. This issue is for this puppet module, not a generic question. Thanks for your input though.

**Comment by mgoritzk** [comment]
@rtoma : also for us this is only a workaround. Adding a different system (Docker) with all its implications cannot be the solution.

**Comment by MAXxATTAXx** [comment]
+1 I have a similar scenario but we have split the ingest of different types of events per instance, as well as having a shipper and indexing nodes. This would be awesome!

**Comment by pulecp** [comment]
+1

**Comment by jarpy** [comment]
Hopefully [multiple pipeline support in Logstash](https://github.com/elastic/logstash/pull/6525) will eliminate the need for this, and do so in a way that is much less complex and uses much less RAM!

**Comment by elexpander** [comment]
Do you know if there is any other module that implements this feature for logstash 5?

**Comment by jordansissel** [comment]
Needing multiple instances is not necessary once you start using the new
multiple pipelines feature — you can read about it here:
https://www.elastic.co/blog/logstash-multiple-pipelines

**Comment by jarpy** [comment]
The multiple pipelines feature is now mainstream and directly supported by this module, so I'm going to close this issue out.

**Comment by alexharv074** [comment]
@jordansissel , @jarpy Is it possible to use the multiple pipelines feature to implement, all on one machine (I want it to be able to go all on one machine for testing, not production):

``` text
shipper (LS 6.3) => redis => indexer (LS 6.3)
```

? If so, is there an example somewhere of the pipeline config you'd use?

**Comment by alexharv074** [comment]
This post here suggests it is possible https://discuss.elastic.co/t/logstash-multipipline-to-replace-shipper-redis-indexer/117787

**Comment by jarpy** [comment]
As far as I understand it, that should be perfectly achievable. There is no reason that an event can't "leave the building" and then return to be processed by another pipeline.
