### ISSUE TITLE
Support Logstash 1.5.x

### ISSUE THREAD

**Issue by pickypg** [elastic/puppet-logstash#238]
The current Puppet module is limited to only supporting Logstash 1.4.2. [Logstash 1.4.4 and Logstash 1.5.3 are out](https://www.elastic.co/blog/logstash-1-5-3-and-1-4-4-released) and LS 1.5.3 is running on a different Ruby runtime (JRuby), so it would be great to support it!

**Comment by igalic** [comment]
i just updated to 1.5.x without trouble using the released version of this module.

**Comment by stevenpost** [comment]
As far as I can tell from the module code, it doesn't handle the 1.5 plugins, so enabling contrib wouldn't work.

**Comment by electrical** [comment]
Hi guys,

Sorry fo the delay on response from my side.

The current planning is to get the ES puppet module up to a certain level so we can use all the improvements made along the way and use that as a boilerplate for all the other modules to avoid doing duplicate development.

The current Logstash module works fine with LS 1.5 except or the plugin management.
We decided to wait with updating since the plugin parts would only be a few exec calls which can be easy implemented by the users.

I am planning to copy the elasticsearch code into a boilerplate in the next few weeks in such a way we can build on top of that and utilize all the improvements for the next Logstash module.

If there are any other concerns or questions, please let me know.

**Comment by michakrause** [comment]
Any progress on this?

**Comment by electrical** [comment]
@michakrause i'm almost done with extracting the ES puppet module into a skeleton and then I'll be able to completely re-do the logstash module.
This will include support for LS 1.5 / 2.x and also the multi instance support that has been requested.

**Comment by michakrause** [comment]
@electrical is there anything I can do to help?

**Comment by jarpy** [comment]
Thanks everyone for your extreme patience.

Logstash 1.5 is now supported on the `master` branch of this module.

I'll release a packaged version on the Forge soon, for those who prefer Forge-based installs.
