### ISSUE TITLE
Has elastic abandoned this puppet module?

### ISSUE THREAD

**Issue by dbeckham** [elastic/puppet-logstash#240]
It seems to me that Elastic has abandoned this module. Logstash 1.5 has been out for months, but there has been zero movement in this puppet module.  The Elasticsearch puppet module was release a good while ago as well, so the idea that they are "waiting" to merge functionality seems more like, "doesn't really care about it."

I need to upgrade my Logstash cluster to the latest versions, but unfortunately, I made the mistake of investing time into using this module instead of rolling my own.  I keep waiting, assuming that an update is around the corner, but that update *never* comes.

Can the maintainers be honest with us? If you've abandoned this module, tell us so that I can give up on and and go implement my own.

**Comment by electrical** [comment]
Hi @dbeckham ,
I'm very sorry you have the feeling we abandoned the module.
I can ensure you this is not the case.
The ES puppet module is currently under heavy development and we recently released version 0.9.9
The current planning is to get the ES puppet module up to a certain level so we can use all the improvements made along the way and use that as a boilerplate for all the other modules to avoid doing duplicate development.
We are also focussing on adding a new module for one of the commercial plugins ( Shield ) of elasticsearch to make it easier for users to manage that part.

The current Logstash module works fine with LS 1.5 except or the plugin management.
We decided to wait with updating since the plugin parts would only be a few exec calls which can be easy implemented by the users.

I am planning to copy the elasticsearch code into a boilerplate in the next few weeks in such a way we can build on top of that and utilize all the improvements for the next Logstash module.

I hope this answers your question.
If you have any other concerns or questions, please let me know.

**Comment by tylerwalts** [comment]
Verified:  I was able to test out 1.5 using the existing module just by updating the `package_url` param to be the latest rpm from the downloads site:  https://www.elastic.co/downloads/logstash

**Comment by cdenneen** [comment]
@electrical Any update? It's been a few months and with Logstash moving aggresively towards LS 2.x this module needs to catch up soon because it's becoming hard to use it to maintain configuration.
The elasticsearch instance template seems like it will fix the issue with instances being removed from this module so that is a really desired feature.
Hopefully the boiler plate template is ready to start testing with LS 1.5.x and 2.x, Puppet 4, etc.

**Comment by alexharv074** [comment]
@electrical I am in the same boat here. I decided to stay with Logstash 1.4 simply because this module isn't ready.  If you could give me a hand, however, I might be able help to build in some of the missing features.  I also plan to write a series of blog posts showing how I've built a scalable logstash cluster using these Puppet modules.

**Comment by cdenneen** [comment]
Alex I have successfully installed Logstash 2.x with this module.
I would however like to see this module update as planned to support all
the additons that were added to elasticsearch module.
Only thing majorly missing here is the plugin install which is in the ES
module and for time being I've written my own wrapper around his to get
that functionality to work.

**Comment by jarpy** [comment]
Hello! After an epic journey, the module now has basic support for Logstash 2.x, and the new plugin system in particular.

This is now available as version `0.6.0` on the Puppet Forge, or fresh from right here on Github, naturally.

I am truly sorry for the amount of time that has ticked away here.
