### ISSUE TITLE
which release supports logstash 5.x

### ISSUE THREAD

**Issue by kvvsprakash** [elastic/puppet-logstash#316]
Hi,

Which puppet module release version we can use for logstash 5.x. Is it available already ?

**Comment by flysen** [comment]
I was just about to ask the same...

**Comment by jarpy** [comment]
Hi @kvvsprakash, @flysen and all,

There is no released version with 5.x support currently, sorry. Work is ongoing in #312 to support the new version of Logstash. The state-of-the-art code is currently in the `5.x` branch of this module, to separate it from the stable Logstash 2.x compatible code in the `master` branch.

The 5.x code is now working reasonably well in many cases, but it isn't release quality yet, since we still have some [acceptance test failures](https://travis-ci.org/elastic/puppet-logstash/builds/178757411) (which thankfully are more about the tests than the code itself), and the in-line documentation is not yet updated. Please feel free to try out the `5.x` branch if you're interested, as I would absolutely love to get feedback and bug reports from you if you have time to try it out. Obviously, I wouldn't recommend running it against your production fleet at this stage! 

Please come and join the conversation in #312 if you like.
