### ISSUE TITLE
Hiera for Pattenfile

### ISSUE THREAD

**Issue by smitjainsj** [elastic/puppet-logstash#326]
Hi first I would thank you for the work on puppet module for logstash.
I am using hiera for logstash pattern and I don't see hiera being called although my other configuration are pulled fine.

```
logstash::patternfile:
 'example':
     source: 'puppet:///modules/logstash/example'
```

but when I call the same from site.pp it works. I hope you can help here.

OS : Ubuntu 14.04
Puppet: 4.5

**Comment by jarpy** [comment]
Hi @smitjainsj,
You're welcome!

I need to make a few assumptions here about what you're doing, so please forgive me if I get anything wrong.

It looks like you are using the yaml backend for Hiera (like most people), no problems there. I'm guessing that you are successfully doing things like this to configure the Logstash module:

``` yaml
logstash::manage_repo: true
logstash::repo_version: 5.x
```

That works because of Puppet and Hiera's [automatic parameter lookup](https://docs.puppet.com/hiera/3.2/puppet.html#automatic-parameter-lookup). That only works for class parameters, though. It's not a complete replacement for the manifest syntax, so you can't just declare a pattern file in hiera and get a result. All that does is define a hash variable, but nobody is looking it up and doing anything with it.

You, as the developer, can, however, choose to lookup variables like that and do very useful things with them indeed! The [`create_resources` function](https://docs.puppet.com/puppet/latest/function.html#createresources) is the missing link here. You can declare a hash containing several of a particular resource like this:

``` yaml
my_patternfiles:
  example_one:
    source: puppet:///modules/site_patternfiles/example_one
  example_two:
    source: puppet:///modules/site_patternfiles/example_two
```

...then look them up from Hiera in your manifest:

``` puppet
$my_patternfiles = hiera('my_patternfiles')
```

... and then pass them to `create_resources`:
```` puppet
create_resources(logstash::patternfile, $my_patternfiles)
````

Let me know if that works for you.

**Comment by smitjainsj** [comment]
Thanks @jarpy  I am really grateful that you assisted me with this problem. I am not very experienced in puppet though, I am making just making efforts to use it as well as I can.
I will implement as you wrote above and will update on this thread .
Thanks again.
