### ISSUE TITLE
Ability to Remove Logstash::Configfile resources.

### ISSUE THREAD

**Issue by corey-hammerton** [elastic/puppet-logstash#329]
A recent change in the workflow of my logstash configurations has resulted in the removal of an existing configuration in replacement of new ones. However, upon review of https://github.com/elastic/puppet-logstash/blob/master/manifests/configfile.pp there is no `ensure` parameter, nor is `$config_dir` recursively purged of unmanaged files. Had to manually remove the files as a workaround.

Requesting to add an `ensure` to `manifests/configfile.pp` to add the ability to remove unwanted config files. Can apply to `manifests/patternfile.pp' too.

**Comment by jarpy** [comment]
Hi @corey-hammerton,

Rather than individually setting config files to `ensure => absent`, it's [possible to set](https://github.com/elastic/puppet-logstash/blob/e8f13cdfa2da22a2a324ed75235e2cfd802a8a2e/manifests/init.pp#L57) `logstash::purge_config: true`, thus always cleaning up any files that aren't explicitly declared in your manifests.

Is that a good fit for your current workflow? Is it set and not working for some reason? We certainly intend to have recursive purging as an option, so if there's a bug in [the implementation](https://github.com/elastic/puppet-logstash/blob/818f97f5f9b7b2f55761c51c61a3b04f4f837e96/manifests/config.pp#L20-L28), I'd love to know.

Actually, looking at that code, it only triggers when `logstash::ensure => present`. Are you using a different value?

Thanks.

**Comment by corey-hammerton** [comment]
I am using `logstash::purge_config: true` since it is default. I didn't realise this was there, thank you.
