### ISSUE TITLE
Java installation handling

### ISSUE THREAD

**Issue by SimonHoenscheid** [elastic/puppet-logstash#341]
The Elasticsearch module handles the java installation, the Logstash module does not. Is that a decision which has been made for purpose or just a missing feature?

**Comment by SimonHoenscheid** [comment]
@jarpy @electrical do you have any information on this?

**Comment by jarpy** [comment]
Not handling Java installation is by design (even though it still exists in the Elasticsearch module).

For me, one of the largest sources of pain in the Puppet community is modules that cause duplicate resource declarations by over-extending their scope. It's true that Java is a requirement for Logstash, but that doesn't mean the Logstash module should directly install it. All the logic we should ever need is nicely encapsulated in [puppetlabs/java](https://forge.puppet.com/puppetlabs/java). Embedding a (less complete) implementation of the same logic in the Logstash module is a waste of effort and a source of resource conflicts.

This is the best description of the issue I've seen: https://www.youtube.com/watch?v=v9LB-NX4_KQ&feature=youtu.be&t=44m30s

In fact, as a Puppet developer, that whole video kinda changed my life. :)

**Comment by SimonHoenscheid** [comment]
Ok, so I would suggest to add a snippet to the Readme about that. I will do a PR
