### ISSUE TITLE
there is no "${logstash::home_dir}/bin/system-install" with logstash 2.2.4

### ISSUE THREAD

**Issue by c4m4** [elastic/puppet-logstash#364]
I am using this module, but fails, because ${logstash::home_dir}/bin/system-install doesn't exist

**Comment by jarpy** [comment]
I'm afraid the current of the module does not support Logstash 2. You can still get the [legacy module on Puppet Forge](https://forge.puppet.com/elasticsearch/logstash) if you need it. If at all possible though, I encourage you to upgrade to Logstash 5 or 6 and use the latest module.

**Comment by c4m4** [comment]
But if we check the logstash version used is 2.2, we can skip the execution of system-install

**Comment by jarpy** [comment]
There's a lot more to it than that. The reason that script exists in Logstash 5 is because Logstash 5 introduced a completely new init system. Logstash 2 didn't actually support systemd at all, and simply relied on backward compatibility support for SysV Init scripts. The changes were so wide reaching that maintaining support for both versions in the same Puppet module version proved extremely difficult. It was so difficult in fact, that we made the decision to only support Logstash 5 in the version 5 module, and to retain the old module in a legacy state for people using Logstash 2.

All of that is quite historical now anyway, since Logstash 2 itself has been [end-of-life for some time](https://www.elastic.co/support/eol) and is unsupported in general.
